######################################################################
##
## Filename: top_system1_tb.udo
## Created on: Fri Nov 14 1:42:18 AM Romance Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
