######################################################################
##
## Filename: gen_dir_tb.udo
## Created on: Sun Dec 07 4:05:34 PM Romance Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
