######################################################################
##
## Filename: dpram_mem_tb.udo
## Created on: Fri Dec 05 1:31:55 PM Romance Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
