######################################################################
##
## Filename: cnt_dpram_tb.udo
## Created on: Mon Dec 15 10:10:47 PM Romance Standard Time 2014
##
## Auto generated by Project Navigator for Post-Route Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
