######################################################################
##
## Filename: cnt_dac.udo
## Created on: Fri Dec 12 12:52:43 PM Romance Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
