######################################################################
##
## Filename: cnt_dac_tb.udo
## Created on: Fri Dec 12 10:15:56 AM Romance Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
