######################################################################
##
## Filename: cnt_dac_tb.udo
## Created on: Thu Dec 11 2:53:44 PM Romance Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
