######################################################################
##
## Filename: cnt_dac_tb.udo
## Created on: Mon Dec 01 12:11:59 PM Romance Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
